version: '3.8'
services:
  postgres:
    container_name: postgres_binar
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  platypus:
    depends_on:
      - postgres
      - platypus_migration
    build: .
    env_file: 
      - .env
    command: "npm run start:dev"
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8080:8080

  platypus_migration:
    depends_on:
      - postgres
    build: .
    env_file:
      - .env
    command: sh -c "npm run db:migrate && npm run db:seed"
    restart: on-failure

volumes:
  postgres: